"""add etag to files

Revision ID: 294352a40358
Revises: 9de98dd97d57
Create Date: 2025-09-03 13:01:14.099331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294352a40358'
down_revision: Union[str, None] = '9de98dd97d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('etag', sa.String(length=128), nullable=True))
    op.drop_constraint(op.f('files_storage_key_key'), 'files', type_='unique')
    op.create_index(op.f('ix_files_storage_key'), 'files', ['storage_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_storage_key'), table_name='files')
    op.create_unique_constraint(op.f('files_storage_key_key'), 'files', ['storage_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('files', 'etag')
    # ### end Alembic commands ###
