"""add thumbnail_key col

Revision ID: 9de98dd97d57
Revises: f018218b2b3c
Create Date: 2025-09-03 11:56:11.325000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de98dd97d57'
down_revision: Union[str, None] = 'f018218b2b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('thumbnail_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'thumbnail_key')
    # ### end Alembic commands ###
