"""add storage_key to files

Revision ID: f018218b2b3c
Revises: e788a5c94ec0
Create Date: 2025-08-20 15:48:23.538539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f018218b2b3c'
down_revision: Union[str, None] = 'e788a5c94ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('storage_key', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'files', ['storage_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_column('files', 'storage_key')
    # ### end Alembic commands ###
